AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

# Allow *VALID_CONFIG_KEYS.keys
Lint/AmbiguousOperator:
  Enabled: false

# server interceptors have higher ABC
Metrics/AbcSize:
  Max: 50

# This cop conflicts with other cops
Layout/LineLength:
  Enabled: false

# server interceptor requires this length
Metrics/MethodLength:
  Max: 30

# New rubocop-required cops
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
